In [1]:
# import Dependencies
from bs4 import BeautifulSoup
import requests
import pandas as pd
import re
from sqlalchemy import create_engine

In [2]:
# create a function that can be reused for scraping the data
def get_html_data(url):
    response = requests.get(url)
    return BeautifulSoup(response.text, "html5lib")

### Source: The Washington Post

* http://stats.washingtonpost.com/fb/glossary.asp

In [3]:
player_position_url = 'http://stats.washingtonpost.com/fb/glossary.asp'

pp_response = get_html_data(player_position_url)
# print(pp_response.prettify())

<html>
 <head>
  <script type="text/javascript">
   var strSport = "NFL";
	var strSportName = "NFL";
	var sSHSSportName = "Football";
	var sSHSLeagueName = "NFL";
	var sSHSPageName = "Glossary";
  </script>
  <meta content="IE=edge,chrome=1" http-equiv="X-UA-Compatible"/>
  <meta charset="utf-8"/>
  <meta content="width=device-width, initial-scale=1.0, user-scalable=yes, minimum-scale=0.5, maximum-scale=2.0" id="viewport" name="viewport"/>
  <title>
  </title>
  <script type="text/javascript">
   document.title = sSHSSportName + " | " + sSHSLeagueName + " | " + sSHSPageName + " - The Washington Post";
  </script>
  <meta content="unsafe-url" name="referrer"/>
  <meta content="Washington Capitals, Washington Nationals, Washington Redskins, DC United , Washington Wizards, baseball, football, hockey, soccer, golf, basketball, college football, college basketball, NBA news, MLB news, NFL news, NHL news, MLS news, Nationals, Redskins, Capitals, Wizards, D.C. United, high school sports,college sports,track and field, hoyas, terps, cavaliers, college sports news, dc sports news, dc sports" name="keywords"/>
  <meta content="Washington Capitals, Washington Nationals, Washington Redskins, DC United , Washington Wizards, baseball, football, hockey, soccer, golf, basketball, college football, college basketball, NBA news, MLB news, NFL news, NHL news, MLS news, Nationals, Redskins, Capitals, Wizards, D.C. United, high school sports,college sports,track and field, hoyas, terps, cavaliers, college sports news, dc sports news, dc sports" name="news_keywords"/>
  <meta name="twitter:site" value="@WashingtonPost"/>
  <meta content="summary_large_image" name="twitter:card"/>
  <meta content="" property="og:type"/>
  <meta content="Washington Post" property="og:site_name"/>
  <meta content="" name="magnet"/>
  <meta content="https://www.facebook.com/washingtonpost" property="article:publisher"/>
  <meta content="41245586762" property="fb:app_id"/>
  <meta content="4403963" property="fb:admins"/>
  <meta content="500835072" property="fb:admins"/>
  <meta content="free" property="article:content_tier"/>
  <link href="/pb/resources/json/desktop-notifications-manifest.json" rel="manifest"/>
  <meta content="Washington Capitals, Washington Nationals, Washington Redskins, DC United , Washington Wizards, baseball, football, hockey, soccer, golf, basketball, college football, college basketball, NBA news, MLB news, NFL news, NHL news, MLS news, Nationals, Redskins, Capitals, Wizards, D.C. United, high school sports,college sports,track and field, hoyas, terps, cavaliers, college sports news, dc sports news, dc sports" name="news_keywords"/>
  <meta content="The Washington Post Sports section provides sports news, video, scores, analysis and updates about high school, college, and pro sports teams, including the Capitals, Nationals, Redskins, United and Wizards. Post Sports also offers blogs and discussions about the latest sports news." name="description"/>
  <meta content="true" name="external"/>
  <link href="http://www.washingtonpost.com/sports/" itemprop="url" rel="canonical"/>
  <meta content="http://www.washingtonpost.com/sports/" property="og:url"/>
  <meta content="https://www.washingtonpost.com/pbox.php?url=https://www.washingtonpost.com/pb/resources/img/twp-social-share.png&amp;w=1484&amp;op=resize&amp;opt=1&amp;filter=antialias&amp;t=20170517" itemprop="image" property="og:image"/>
  <meta content="Sports" property="og:title"/>
  <meta content="The Washington Post Sports section provides sports news, video, scores, analysis and updates about high school, college, and pro sports teams, including the Capitals, Nationals, Redskins, United and Wizards. Post Sports also offers blogs and discussions about the latest sports news." itemprop="description" name="description"/>
  <meta content="The Washington Post Sports section provides sports news, video, scores, analysis and updates about high school, college, and pro sports teams, including the Capitals, Nationals, Redskins, United and Wizards. Post Sports also offers blogs and discussions about the latest sports news." property="og:description"/>
  <link href="https://www.washingtonpost.com/favicon.ico" rel="shortcut icon"/>
  <link href="https://www.washingtonpost.com/rw/sites/twpweb/css/stats.css" rel="stylesheet" type="text/css"/>
  <script src="https://www.washingtonpost.com/1h/twp-internal.js" type="text/javascript">
  </script>
  <script>
   thisNode = 'sports/stats';
        commercialNode = 'sports/stats';
  </script>
  <script type="text/javascript">
   var wp_page_name = "wp - stats - " + document.location.pathname;
        var wp_channel = "sports";
        var wp_subsection = "sports - stats";
        var wp_source = "stats inc";
        var wp_content_type = 'graphic';
        var wp_hierarchy = "sports|stats";
        var wp_application = "partner - stats inc";
  </script>
  <script src="https://www.washingtonpost.com/wp-srv/analytics/main.js" type="text/javascript">
  </script>
  <script type="text/javascript">
   TWP.Analytics.init();
  </script>
  <script src="https://wapo.zeustechnology.com/main.js">
  </script>
  <style type="text/css">
   /*#shell {
                width: 992px;
                margin: 0 auto;
                background: white;
            }
          #header-v3 {
                height: 182px;
                margin-bottom: 10px;
            }

            #header-v3.ie7 {
                height: auto;
            }
            #leaderboard,
            #slug_leaderboard {
                width: 992px;
                text-align: center;
                padding: 0 0 10px
            }*/
        #bread_crumbs {
            max-width: 1000px;
            width: 100%;
            padding-top: 2px;
            padding-left: 10px;
            color: #0D3159;
            font-family: arial, ms-sans-serif, sans-serif;
            font-size: 11px;
            font-weight: bold;
            padding-bottom: 2px;
            border-bottom: 1px solid #CCCCCC;
            margin-bottom: 5px;
            margin: auto;
        }

        #bread_crumbs a {
            text-decoration: none;
            color: #0D3159;
        }
        #content_body {
            max-width: 1400px;
            margin: auto;
        }
  </style>
 </head>
 <body>
  <div id="shell">
   <div class="external" data-config="section=sports&amp;hotTopics=false" id="header-v3">
   </div>
   <!--LEADERBOARD AD BEGIN-->
   <wp-ad id="slug_leaderboard">
   </wp-ad>
   <!--LEADERBOARD AD END-->
   <div id="content_body">
    <div id="bread_crumbs">
     <a href="http://www.washingtonpost.com">
      washingtonpost.com
     </a>
     &gt;
     <a href="http://www.washingtonpost.com/sports/">
      Sports
     </a>
    </div>
    <div id="wrapperMainLeft" style="padding-right:10px;">
     <div id="wrapperInnerLeft" style="display: inline">
      <link href="http://hosted.stats.com/config/shsResponsive.css" rel="stylesheet" type="text/css"/>
      <script src="http://hosted.stats.com/config/responsive_js/jquery-1.7.2.min.js">
      </script>
      <script src="/shsNav_noJQconflict.js">
      </script>
      <link href="https://static-hosted.stats.com/config/shsdefault.css" rel="stylesheet" type="text/css"/>
      <link href="/shs.css" rel="stylesheet" type="text/css"/>
      <link href="https://static-hosted.stats.com/config/pfbdefault.css" rel="stylesheet" type="text/css"/>
      <link href="/pfb.css" rel="stylesheet" type="text/css"/>
      <div class="shs_sportNav">
       <div class="shs_sportNavBlock">
        <h2>
         NFL Football
        </h2>
        <ul class="shs_sportNavList">
         <li class="shsHomeLink">
          <a href="/fb/front.asp">
           Home
          </a>
         </li>
         <li class="shsScoreboardLink">
          <a href="/fb/scoreboard.asp">
           Scoreboard
          </a>
         </li>
         <li class="shsStatsLink">
          <a href="/fb/index.asp">
           Stats
          </a>
         </li>
         <li class="shsStandingsLink">
          <a href="/fb/standings.asp">
           Standings
          </a>
         </li>
         <li class="shsTeamsLink">
          <a href="/fb/teams.asp">
           Teams
          </a>
         </li>
         <li class="shsPlayersLink">
          <a href="/fb/players.asp">
           Players
          </a>
         </li>
         <li class="shsPlayerNewsLink">
          <a href="/fb/notes.asp">
           Player News
          </a>
         </li>
         <li class="shsInjuriesLink">
          <a href="/fb/recentinj.asp">
           Injuries
          </a>
         </li>
         <li class="shsTransactionsLink">
          <a href="/fb/recenttrans.asp">
           Transactions
          </a>
         </li>
         <li class="shsOddsLink">
          <a href="/fb/odds.asp">
           Odds
          </a>
         </li>
         <li class="moreOptions">
          <a href="#">
           More...
          </a>
         </li>
         <li class="lessOptions">
          <a href="#">
           Close X
          </a>
         </li>
        </ul>
        <script type="text/javascript">
         var shsObj = {scrolltop: 0};
				jq172(document).ready(function(){
				  jq172(".moreOptions").click(function(e){
				  	e.preventDefault();
					jq172(this).parent().parent().toggleClass('active');
					shsObj.scrolltop = jq172('body').scrollTop();
					jq172(".shs_sportNavList li").not(".moreOptions, .lessOptions").click(function(){
						jq172('body').scrollTop(shsObj.scrolltop);
					});
				  });
				   jq172(".lessOptions").click(function(){
					jq172(this).parent().parent().toggleClass('active');
				  });
				});
        </script>
       </div>
      </div>
      <div id="shsBody">
       <div id="shsGlossary">
        <h2>
         Football Glossary
        </h2>
        <table style="width: 100%">
         <tbody>
          <tr>
           <td style="vertical-align: top">
            <table cellspacing="0" class="shsTable">
             <tbody>
              <tr class="shsTableTtlRow">
               <td colspan="2">
                Stat Abbreviations
               </td>
              </tr>
              <tr class="shsColTtlRow">
               <td style="width: 10%">
                Abbreviation
               </td>
               <td style="width: 90%">
                Definition
               </td>
              </tr>
              <tr class="shsRow0Row">
               <td>
                <strong>
                 A
                </strong>
               </td>
               <td>
                Assist
               </td>
              </tr>
              <tr class="shsRow1Row">
               <td>
                <strong>
                 Att
                </strong>
               </td>
               <td>
                Attempts
               </td>
              </tr>
              <tr class="shsRow0Row">
               <td>
                <strong>
                 Avg
                </strong>
               </td>
               <td>
                Average
               </td>
              </tr>
              <tr class="shsRow1Row">
               <td>
                <strong>
                 Big
                </strong>
               </td>
               <td>
                Big Plays
               </td>
              </tr>
              <tr class="shsRow0Row">
               <td>
                <strong>
                 Blk
                </strong>
               </td>
               <td>
                Blocked Kick
               </td>
              </tr>
              <tr class="shsRow1Row">
               <td>
                <strong>
                 BT
                </strong>
               </td>
               <td>
                Broken Tackles
               </td>
              </tr>
              <tr class="shsRow0Row">
               <td>
                <strong>
                 BT%
                </strong>
               </td>
               <td>
                Broken Tackle Percentage
               </td>
              </tr>
              <tr class="shsRow1Row">
               <td>
                <strong>
                 Cmp
                </strong>
               </td>
               <td>
                Completions
               </td>
              </tr>
              <tr class="shsRow0Row">
               <td>
                <strong>
                 FC
                </strong>
               </td>
               <td>
                Fair Catches
               </td>
              </tr>
              <tr class="shsRow1Row">
               <td>
                <strong>
                 Lost
                </strong>
               </td>
               <td>
                Fumbles-Lost
               </td>
              </tr>
              <tr class="shsRow0Row">
               <td>
                <strong>
                 FF
                </strong>
               </td>
               <td>
                Forced Fumbles
               </td>
              </tr>
              <tr class="shsRow1Row">
               <td>
                <strong>
                 FG
                </strong>
               </td>
               <td>
                Field Goal
               </td>
              </tr>
              <tr class="shsRow0Row">
               <td>
                <strong>
                 FGA
                </strong>
               </td>
               <td>
                Field Goal Attempt
               </td>
              </tr>
              <tr class="shsRow1Row">
               <td>
                <strong>
                 FR
                </strong>
               </td>
               <td>
                Fumbles Recovered
               </td>
              </tr>
              <tr class="shsRow0Row">
               <td>
                <strong>
                 Fum
                </strong>
               </td>
               <td>
                Fumbles
               </td>
              </tr>
              <tr class="shsRow1Row">
               <td>
                <strong>
                 G
                </strong>
               </td>
               <td>
                Games
               </td>
              </tr>
              <tr class="shsRow0Row">
               <td>
                <strong>
                 Grs Avg
                </strong>
               </td>
               <td>
                Gross Punting Average
               </td>
              </tr>
              <tr class="shsRow1Row">
               <td>
                <strong>
                 Int
                </strong>
               </td>
               <td>
                Interception
               </td>
              </tr>
              <tr class="shsRow0Row">
               <td>
                <strong>
                 Int %
                </strong>
               </td>
               <td>
                Interception Percentage
               </td>
              </tr>
              <tr class="shsRow1Row">
               <td>
                <strong>
                 In20
                </strong>
               </td>
               <td>
                Inside Opponent's 20
               </td>
              </tr>
              <tr class="shsRow0Row">
               <td>
                <strong>
                 IntYd
                </strong>
               </td>
               <td>
                Interception Return Yards
               </td>
              </tr>
              <tr class="shsRow1Row">
               <td>
                <strong>
                 Lg
                </strong>
               </td>
               <td>
                Longest
               </td>
              </tr>
              <tr class="shsRow0Row">
               <td>
                <strong>
                 Net Avg
                </strong>
               </td>
               <td>
                Net Punting Average
               </td>
              </tr>
              <tr class="shsRow1Row">
               <td>
                <strong>
                 Opp
                </strong>
               </td>
               <td>
                Opponent
               </td>
              </tr>
              <tr class="shsRow0Row">
               <td>
                <strong>
                 Pct
                </strong>
               </td>
               <td>
                Percentage
               </td>
              </tr>
              <tr class="shsRow1Row">
               <td>
                <strong>
                 PD
                </strong>
               </td>
               <td>
                Pass Defensed
               </td>
              </tr>
              <tr class="shsRow0Row">
               <td>
                <strong>
                 Prv
                </strong>
               </td>
               <td>
                Previous
               </td>
              </tr>
              <tr class="shsRow1Row">
               <td>
                <strong>
                 Pts
                </strong>
               </td>
               <td>
                Points
               </td>
              </tr>
              <tr class="shsRow0Row">
               <td>
                <strong>
                 Rcv
                </strong>
               </td>
               <td>
                Recovery
               </td>
              </tr>
              <tr class="shsRow1Row">
               <td>
                <strong>
                 Rec
                </strong>
               </td>
               <td>
                Reception
               </td>
              </tr>
              <tr class="shsRow0Row">
               <td>
                <strong>
                 Ret
                </strong>
               </td>
               <td>
                Return
               </td>
              </tr>
              <tr class="shsRow1Row">
               <td>
                <strong>
                 Rnk
                </strong>
               </td>
               <td>
                Ranking
               </td>
              </tr>
              <tr class="shsRow0Row">
               <td>
                <strong>
                 Rtg
                </strong>
               </td>
               <td>
                Rating
               </td>
              </tr>
              <tr class="shsRow1Row">
               <td>
                <strong>
                 Sk
                </strong>
               </td>
               <td>
                Sacks
               </td>
              </tr>
              <tr class="shsRow0Row">
               <td>
                <strong>
                 Stf
                </strong>
               </td>
               <td>
                Stuffs
               </td>
              </tr>
              <tr class="shsRow1Row">
               <td>
                <strong>
                 SckYds
                </strong>
               </td>
               <td>
                Sack Yardage
               </td>
              </tr>
              <tr class="shsRow0Row">
               <td>
                <strong>
                 TB
                </strong>
               </td>
               <td>
                Touchback
               </td>
              </tr>
              <tr class="shsRow1Row">
               <td>
                <strong>
                 TD
                </strong>
               </td>
               <td>
                Touchdown
               </td>
              </tr>
              <tr class="shsRow0Row">
               <td>
                <strong>
                 Tgt
                </strong>
               </td>
               <td>
                Target
               </td>
              </tr>
              <tr class="shsRow1Row">
               <td>
                <strong>
                 Tgt Avg
                </strong>
               </td>
               <td>

In [4]:
# results are returned as an iterable list
pp_results = pp_response.find_all('table', class_="shsTable")

# print(pp_results)
# print(pp_results[1].prettify())   

pp_df = pd.read_html(str(pp_results[1]))
pp_df = pp_df[0]
pp_df.head()

                        0                       1
0  Position Abbreviations  Position Abbreviations
1            Abbreviation                Position
2                      QB             Quarterback
3                      RB            Running Back
4                      FB                Fullback

In [5]:
# rename columns
pp_df = pp_df.rename(columns={0: "abbreviation", 1 : "position"}) 

# set index to abbreviation
pp_df.set_index("abbreviation", inplace=True)
pp_df.drop(['Position Abbreviations', 'Abbreviation'], inplace=True)

pp_df.head()

                   position
abbreviation
QB              Quarterback
RB             Running Back
FB                 Fullback
WR            Wide Receiver
TE                Tight End

In [6]:
# pp_df.reset_index(inplace=True)
# pp_df.head()

### Super Bowl Winners
### Source: Topend Sports
* The Super Bowl is the annual championship game of the National Football League (NFL). 
* Below is a list of all the winners of the Super Bowl since Green Bay won the first in 1967. 
* The years listed indicate the year the Super Bowl was played, the regular season is played during the year before.

In [7]:
# Superbowl winning teams with scores 
sb_url = 'https://www.topendsports.com/events/super-bowl/winners-list.htm'
sb_response = get_html_data(sb_url)

# print(sb_response.prettify())

In [8]:
# results are returned as an iterable list
sb_results = sb_response.find_all('table', class_="list")

# print(sb_results[0].prettify())

# read html to convert the data to dataframe - but this return a list
sb_df = pd.read_html(str(sb_results))

# convert the list to a dataframe
sb_df = sb_df[0]

# display the first 5 rows of dataframe
sb_df.head()

   Year   No.                Winner            Opposition  Score       Venue
0  2020   LIV    Kansas City Chiefs   San Francisco 49ers  31-20       Miami
1  2019  LIII  New England Patriots      Los Angeles Rams   13-3     Atlanta
2  2018   LII   Philadelphia Eagles  New England Patriots  41-33   Minnesota
3  2017    LI  New England Patriots       Atlanta Falcons  34-28       Texas
4  2016     L        Denver Broncos     Carolina Panthers  24-10  California

In [9]:
# rename columns
sb_df = sb_df.rename(columns={'Year' : 'year',
                              'No.' : 'sb_no', 
                              'Winner': "winner_team", 
                              "Opposition" : "loser_team",
                              }) 
sb_df.head()

   year sb_no           winner_team            loser_team  Score       Venue
0  2020   LIV    Kansas City Chiefs   San Francisco 49ers  31-20       Miami
1  2019  LIII  New England Patriots      Los Angeles Rams   13-3     Atlanta
2  2018   LII   Philadelphia Eagles  New England Patriots  41-33   Minnesota
3  2017    LI  New England Patriots       Atlanta Falcons  34-28       Texas
4  2016     L        Denver Broncos     Carolina Panthers  24-10  California

In [10]:
# Data has some special characters in Score field. But we need to retain the '-' as is to split the score into 2 fields
sb_df['Score'] = sb_df['Score'].str.replace(r"[^a-zA-Z0-9]+", '-')
sb_df.head()

   year sb_no           winner_team            loser_team  Score       Venue
0  2020   LIV    Kansas City Chiefs   San Francisco 49ers  31-20       Miami
1  2019  LIII  New England Patriots      Los Angeles Rams   13-3     Atlanta
2  2018   LII   Philadelphia Eagles  New England Patriots  41-33   Minnesota
3  2017    LI  New England Patriots       Atlanta Falcons  34-28       Texas
4  2016     L        Denver Broncos     Carolina Panthers  24-10  California

In [11]:
# split the score in to 2 fields: score_won and score_lost
def get_winner_score(Score):
    return Score.split("-")[0]

def get_loser_score(Score):
    return Score.split("-")[1]

# Use the labda function to apply the above function to split the score in the dataframe
sb_df['winner_score'] = sb_df['Score'].apply(lambda x: f"{get_winner_score(x)}")
sb_df['loser_score'] = sb_df['Score'].apply(lambda x: f"{get_loser_score(x)}")

sb_df.head()

,year,sb_no,winner_team,loser_team,Score,Venue,winner_score,loser_score
0,2020,LIV,Kansas City Chiefs,San Francisco 49ers,31-20,Miami,31,20
1,2019,LIII,New England Patriots,Los Angeles Rams,13-3,Atlanta,13,3
2,2018,LII,Philadelphia Eagles,New England Patriots,41-33,Minnesota,41,33
3,2017,LI,New England Patriots,Atlanta Falcons,34-28,Texas,34,28
4,2016,L,Denver Broncos,Carolina Panthers,24-10,California,24,10

In [12]:
# As we split the score into 2 different columns we don't need original score column
# sb_df.drop(['Score', 'Year'],axis='columns',inplace=True)

sb_df.drop(['Score', 'Venue'],axis='columns',inplace=True)

# set index to sb_no 
sb_df.set_index("sb_no", inplace=True)
sb_df.head()

,year,winner_team,loser_team,winner_score,loser_score
sb_no,,,,,
LIV,2020,Kansas City Chiefs,San Francisco 49ers,31,20
LIII,2019,New England Patriots,Los Angeles Rams,13,3
LII,2018,Philadelphia Eagles,New England Patriots,41,33
LI,2017,New England Patriots,Atlanta Falcons,34,28
L,2016,Denver Broncos,Carolina Panthers,24,10

In [13]:
# rearrange the columns
sb_df = sb_df[['year', 'winner_team', 'winner_score', 'loser_team', 'loser_score']]
sb_df.head()

,year,winner_team,winner_score,loser_team,loser_score
sb_no,,,,,
LIV,2020,Kansas City Chiefs,31,San Francisco 49ers,20
LIII,2019,New England Patriots,13,Los Angeles Rams,3
LII,2018,Philadelphia Eagles,41,New England Patriots,33
LI,2017,New England Patriots,34,Atlanta Falcons,28
L,2016,Denver Broncos,24,Carolina Panthers,10

In [14]:
sb_df.dtypes

year             int64
winner_team     object
winner_score    object
loser_team      object
loser_score     object
dtype: object

### Source: ESPN
### NFL History - Super Bowl MVPs
* http://www.espn.com/nfl/superbowl/history/mvps

In [15]:
mvp_url = 'http://www.espn.com/nfl/superbowl/history/mvps'
mvp_response = get_html_data(mvp_url)
# print(mvp_response.prettify())

In [16]:
# results are returned as an iterable list
mvp_results = mvp_response.find_all('table', class_="tablehead")

# print(mvp_results[0].prettify())      

# read html and convert it to pandas dataframe
mvp_df = pd.read_html(str(mvp_results))
mvp_df = mvp_df[0]

# rename columns
mvp_df = mvp_df.rename(columns={0: "sb_no", 1 : "mv_player", 2 : "highlights"}) 

# set the value 50 to letter L to be consistent with other super bowl numbers
mvp_df['sb_no'] = mvp_df['sb_no'].replace('50','L', regex=True)
mvp_df.head()

,sb_no,mv_player,highlights
0,Super Bowl Most Valuable Players,Super Bowl Most Valuable Players,Super Bowl Most Valuable Players
1,NO.,PLAYER,HIGHLIGHTS
2,I,"Bart Starr, QB, Green Bay",Two touchdown passes
3,II,"Bart Starr, QB, Green Bay","202 yards passing, 1 TD"
4,III,"Joe Namath, QB, New York Jets",206 yards passing

In [17]:
# set index to sb_no
mvp_df.set_index("sb_no", inplace=True)

# drop the unwanted data
mvp_df.drop(['Super Bowl Most Valuable Players', 'NO.'], inplace=True)

#dispaly the data
mvp_df.head()

                           mv_player                          highlights
sb_no
I          Bart Starr, QB, Green Bay                Two touchdown passes
II         Bart Starr, QB, Green Bay             202 yards passing, 1 TD
III    Joe Namath, QB, New York Jets                   206 yards passing
IV       Len Dawson, QB, Kansas City             142 yards passing, 1 TD
V           Chuck Howley, LB, Dallas  Two interceptions, fumble recovery

In [18]:
# Split the mvp_player column into name of the player, role, and the team
def get_player(mv_player):
    return mv_player.split(",")[0]

def get_position(mv_player):
    return mv_player.split(",")[1]

def get_team(mv_player):
    return mv_player.split(",")[2]

mvp_df['player'] = mvp_df['mv_player'].apply(lambda x: f"{get_player(x)}")
mvp_df['position_abbr'] = mvp_df['mv_player'].apply(lambda x: f"{get_position(x)}")
mvp_df['team'] = mvp_df['mv_player'].apply(lambda x: f"{get_team(x)}")

mvp_df.head()

,mv_player,highlights,player,position_abbr,team
sb_no,,,,,
I,"Bart Starr, QB, Green Bay",Two touchdown passes,Bart Starr,QB,Green Bay
II,"Bart Starr, QB, Green Bay","202 yards passing, 1 TD",Bart Starr,QB,Green Bay
III,"Joe Namath, QB, New York Jets",206 yards passing,Joe Namath,QB,New York Jets
IV,"Len Dawson, QB, Kansas City","142 yards passing, 1 TD",Len Dawson,QB,Kansas City
V,"Chuck Howley, LB, Dallas","Two interceptions, fumble recovery",Chuck Howley,LB,Dallas

In [19]:
# drop mv_player
mvp_df.drop(['mv_player'],axis='columns',inplace=True)
mvp_df.head()

,highlights,player,position_abbr,team
sb_no,,,,
I,Two touchdown passes,Bart Starr,QB,Green Bay
II,"202 yards passing, 1 TD",Bart Starr,QB,Green Bay
III,206 yards passing,Joe Namath,QB,New York Jets
IV,"142 yards passing, 1 TD",Len Dawson,QB,Kansas City
V,"Two interceptions, fumble recovery",Chuck Howley,LB,Dallas

In [20]:
mvp_df = mvp_df[['player', 'position_abbr', 'team', 'highlights']]
mvp_df.head()

,player,position_abbr,team,highlights
sb_no,,,,
I,Bart Starr,QB,Green Bay,Two touchdown passes
II,Bart Starr,QB,Green Bay,"202 yards passing, 1 TD"
III,Joe Namath,QB,New York Jets,206 yards passing
IV,Len Dawson,QB,Kansas City,"142 yards passing, 1 TD"
V,Chuck Howley,LB,Dallas,"Two interceptions, fumble recovery"

In [21]:
# mvp_df.reset_index(inplace=True)
# mvp_df.head()
mvp_df.dtypes

player           object
position_abbr    object
team             object
highlights       object
dtype: object

### Source: Wikipedia
### List of Super Bowl starting quarterbacks
* https://en.wikipedia.org/wiki/List_of_Super_Bowl_starting_quarterbacks

In [22]:
qb_url = 'https://en.wikipedia.org/wiki/List_of_Super_Bowl_starting_quarterbacks'

qb_response = get_html_data(qb_url)
# print(qb_response.prettify())

In [23]:
# results are returned as an iterable list
qb_results = qb_response.find_all('table', class_="wikitable")

# print(qb_results[1].prettify())      

qb_df = pd.read_html(str(qb_results[1]))
qb_df = qb_df[0]
qb_df.head()

,Season,Super Bowl,Winning QB,Team,Losing QB,Team.1
0,1966 AFL/NFL,I,Bart Starr*MVP,Green Bay Packersn,Len Dawson*,Kansas City Chiefsa
1,1967 AFL/NFL,II,Bart Starr*MVP,Green Bay Packersn,Daryle Lamonica,Oakland Raidersa
2,1968 AFL/NFL,III,Joe Namath*MVP,New York Jetsa,Earl Morrall,Baltimore Coltsn
3,1969 AFL/NFL,IV,Len Dawson*MVP,Kansas City Chiefsa,Joe Kapp,Minnesota Vikingsn
4,1970,V,Johnny Unitas*,Baltimore ColtsA,Craig Morton,Dallas CowboysN

In [24]:
# remove the special charachaters from data
qb_df['winner_qb'] = qb_df['Winning QB'].str.replace('\W', ' ')
qb_df['loser_qb'] = qb_df['Losing QB'].str.replace('\W', ' ')
qb_df.head()

,Season,Super Bowl,Winning QB,Team,Losing QB,Team.1,winner_qb,loser_qb
0,1966 AFL/NFL,I,Bart Starr*MVP,Green Bay Packersn,Len Dawson*,Kansas City Chiefsa,Bart Starr MVP,Len Dawson
1,1967 AFL/NFL,II,Bart Starr*MVP,Green Bay Packersn,Daryle Lamonica,Oakland Raidersa,Bart Starr MVP,Daryle Lamonica
2,1968 AFL/NFL,III,Joe Namath*MVP,New York Jetsa,Earl Morrall,Baltimore Coltsn,Joe Namath MVP,Earl Morrall
3,1969 AFL/NFL,IV,Len Dawson*MVP,Kansas City Chiefsa,Joe Kapp,Minnesota Vikingsn,Len Dawson MVP,Joe Kapp
4,1970,V,Johnny Unitas*,Baltimore ColtsA,Craig Morton,Dallas CowboysN,Johnny Unitas,Craig Morton

In [25]:
qb_df.drop(['Winning QB', 'Losing QB'],axis='columns',inplace=True)
qb_df.head()

,Season,Super Bowl,Team,Team.1,winner_qb,loser_qb
0,1966 AFL/NFL,I,Green Bay Packersn,Kansas City Chiefsa,Bart Starr MVP,Len Dawson
1,1967 AFL/NFL,II,Green Bay Packersn,Oakland Raidersa,Bart Starr MVP,Daryle Lamonica
2,1968 AFL/NFL,III,New York Jetsa,Baltimore Coltsn,Joe Namath MVP,Earl Morrall
3,1969 AFL/NFL,IV,Kansas City Chiefsa,Minnesota Vikingsn,Len Dawson MVP,Joe Kapp
4,1970,V,Baltimore ColtsA,Dallas CowboysN,Johnny Unitas,Craig Morton

In [26]:
# rename columns
qb_df = qb_df.rename(columns={"Season" : "year", "Super Bowl" : 'sb_no', 'Team': "winner_team", "Team.1" : "loser_team"}) 
qb_df.head()

,year,sb_no,winner_team,loser_team,winner_qb,loser_qb
0,1966 AFL/NFL,I,Green Bay Packersn,Kansas City Chiefsa,Bart Starr MVP,Len Dawson
1,1967 AFL/NFL,II,Green Bay Packersn,Oakland Raidersa,Bart Starr MVP,Daryle Lamonica
2,1968 AFL/NFL,III,New York Jetsa,Baltimore Coltsn,Joe Namath MVP,Earl Morrall
3,1969 AFL/NFL,IV,Kansas City Chiefsa,Minnesota Vikingsn,Len Dawson MVP,Joe Kapp
4,1970,V,Baltimore ColtsA,Dallas CowboysN,Johnny Unitas,Craig Morton

In [27]:
qb_df = qb_df.replace('MVP','', regex=True)
qb_df = qb_df.replace('AFL/NFL','', regex=True)

qb_df.head()

,year,sb_no,winner_team,loser_team,winner_qb,loser_qb
0,1966,I,Green Bay Packersn,Kansas City Chiefsa,Bart Starr,Len Dawson
1,1967,II,Green Bay Packersn,Oakland Raidersa,Bart Starr,Daryle Lamonica
2,1968,III,New York Jetsa,Baltimore Coltsn,Joe Namath,Earl Morrall
3,1969,IV,Kansas City Chiefsa,Minnesota Vikingsn,Len Dawson,Joe Kapp
4,1970,V,Baltimore ColtsA,Dallas CowboysN,Johnny Unitas,Craig Morton

In [28]:
# the last character of the team name has 'a' or 'n' to nitity afc or nfc. Remove that extra character from team names 
qb_df['winner_team'] = [sub[ : -1] for sub in qb_df['winner_team']] 
qb_df['loser_team'] = [sub[ : -1] for sub in qb_df['winner_team']]

# Update the super bowl number 50 to L
qb_df['sb_no'] = qb_df['sb_no'].replace('50','L', regex=True)

qb_df.head()

,year,sb_no,winner_team,loser_team,winner_qb,loser_qb
0,1966,I,Green Bay Packers,Green Bay Packer,Bart Starr,Len Dawson
1,1967,II,Green Bay Packers,Green Bay Packer,Bart Starr,Daryle Lamonica
2,1968,III,New York Jets,New York Jet,Joe Namath,Earl Morrall
3,1969,IV,Kansas City Chiefs,Kansas City Chief,Len Dawson,Joe Kapp
4,1970,V,Baltimore Colts,Baltimore Colt,Johnny Unitas,Craig Morton

In [29]:
# set index to sb_no
qb_df.set_index("sb_no", inplace=True)
qb_df.tail()

,year,winner_team,loser_team,winner_qb,loser_qb
sb_no,,,,,
LI,2016,New England Patriots,New England Patriot,Tom Brady,Matt Ryan
LII,2017,Philadelphia Eagles,Philadelphia Eagle,Nick Foles,Tom Brady
LIII,2018,New England Patriots,New England Patriot,Tom Brady,Jared Goff
LIV,2019,Kansas City Chiefs,Kansas City Chief,Patrick Mahomes,Jimmy Garoppolo
Super Bowl,Season,Tea,Te,Winning QB,Losing QB

In [30]:
qb_df.drop(['Super Bowl'], inplace=True)
#dispaly the data
qb_df.tail()

,year,winner_team,loser_team,winner_qb,loser_qb
sb_no,,,,,
L,2015,Denver Broncos,Denver Bronco,Peyton Manning,Cam Newton
LI,2016,New England Patriots,New England Patriot,Tom Brady,Matt Ryan
LII,2017,Philadelphia Eagles,Philadelphia Eagle,Nick Foles,Tom Brady
LIII,2018,New England Patriots,New England Patriot,Tom Brady,Jared Goff
LIV,2019,Kansas City Chiefs,Kansas City Chief,Patrick Mahomes,Jimmy Garoppolo

In [31]:
qb_df['year'].astype(str).map(len).head()

sb_no
I      5
II     5
III    5
IV     5
V      4
Name: year, dtype: int64

In [32]:
qb_df['year'] = qb_df['year'].str.strip()

In [33]:
qb_df.dtypes

year           object
winner_team    object
loser_team     object
winner_qb      object
loser_qb       object
dtype: object

### Create database connection

In [34]:
connection_string = "postgres:postgres@localhost:5432/nfl_db"
engine = create_engine(f'postgresql://{connection_string}')

### Load DataFrames into database

In [35]:
pp_df.to_sql(name='player_position', con=engine, if_exists='append', index=True)

In [36]:
sb_df.to_sql(name='sb_winners', con=engine, if_exists='append', index=True)

In [37]:
mvp_df.to_sql(name='most_valuable_player', con=engine, if_exists='append', index=True)

In [38]:
qb_df.to_sql(name='sb_quarterbacks', con=engine, if_exists='append', index=True)